# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: myVariableGroup

steps:
- script: echo Hello, $MY_VARIABLE!
  displayName: 'Run a one-line script'
  env:
    MY_VARIABLE: $(myVariable)

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo My secret variable group variable is $MY_GROUP_VARIABLE
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  env:
    MY_GROUP_VARIABLE: $(myVariableGroupVar)
